spring.application.name=xpeho_formation_spring

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/xpeho_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configuration
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=validate

# Spring Data JDBC - Initialize database
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=
spring.sql.init.platform=postgresql
spring.sql.init.continue-on-error=true

# Swagger UI custom path
springdoc.swagger-ui.path=/api

# OMDB API configuration
omdb.api.key=${OMDB_API_KEY:demo}
