package com.xpeho.xpeho_formation_spring.data.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Data model representing a movie entity in the database.
 * <p>
 * This immutable record class maps directly to the MOVIE table in the database.
 * It serves as the data transfer object between the database layer and the application logic.
 *
 * @author XPEHO
 */
@Table("MOVIE")
public record Movie(
        /**
         * Unique identifier for the movie (primary key).
         * Auto-generated by the database.
         */
        @Id int id,
        /**
         * The title of the movie.
         */
        String title,
        /**
         * The release year of the movie.
         */
        @Column("year") String year,
        /**
         * The IMDb identifier for the movie.
         */
        @Column("imdb_id") String imdbId,
        /**
         * The type of content (e.g., "movie", "series").
         */
        @Column("type") String type,
        /**
         * URL to the movie poster image.
         */
        String poster
) {
}
